FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/oven/bun:1.4.0 AS web-builder

WORKDIR /build/web
COPY web/package.json web/bun.lock ./
RUN bun install --registry https://registry.npmmirror.com --frozen-lockfile
COPY web ./
COPY VERSION /build/VERSION
RUN DISABLE_ESLINT_PLUGIN=true VITE_REACT_APP_VERSION=$(cat /build/VERSION) bun run build

FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/golang:1.26.1-alpine AS go-builder

ENV CGO_ENABLED=0 GO111MODULE=on GOWORK=off GOEXPERIMENT=greenteagc
WORKDIR /build

COPY go.mod go.sum ./
COPY relaykit/go.mod relaykit/go.mod
RUN GOPROXY=https://goproxy.cn,direct go mod download

COPY . .
COPY --from=web-builder /build/web/dist web/dist
RUN go build -ldflags "-s -w -X 'github.com/QuantumNous/new-api/common.Version=$(cat VERSION)'" -o /new-api .

FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates tzdata wget \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates

COPY --from=go-builder /new-api /new-api
COPY LICENSE NOTICE THIRD-PARTY-LICENSES.md /licenses/
EXPOSE 3000
WORKDIR /data
ENTRYPOINT ["/new-api"]
